-- study_seed_v2.sql
-- Run AFTER study_schema.sql and study_seed.sql in Supabase SQL Editor
-- Adds: TypeScript, Git, Docker, Kubernetes, AWS, Next.js, GraphQL,
--       PostgreSQL, Redis, React Native, Kotlin/Android, Spring Boot
-- Plus: DevOps & Cloud category + extra questions for Behavioral, JS, System Design

-- ─── NEW CATEGORY ─────────────────────────────────────────────────────────────
INSERT INTO study_categories (id, title, icon, color, bg_color, sort_order) VALUES
  ('devops_cloud', 'DevOps & Cloud', '☁️', '#0369a1', '#f0f9ff', 8)
ON CONFLICT (id) DO NOTHING;

-- ─── NEW TOPICS ───────────────────────────────────────────────────────────────
INSERT INTO study_topics (id, category_id, title, sort_order) VALUES
  -- Technical additions
  ('typescript',       'technical',    'TypeScript',         11),
  ('git',              'technical',    'Git',                12),
  ('nextjs',           'technical',    'Next.js',            13),
  ('graphql',          'technical',    'GraphQL',            14),
  ('react_native',     'technical',    'React Native',       15),
  ('spring_boot',      'technical',    'Spring Boot',        16),
  ('django_python',    'technical',    'Django',             17),
  -- Database additions
  ('postgresql',       'database',     'PostgreSQL',          3),
  ('redis',            'database',     'Redis',               4),
  -- DevOps & Cloud
  ('docker',           'devops_cloud', 'Docker',              1),
  ('kubernetes',       'devops_cloud', 'Kubernetes',          2),
  ('aws',              'devops_cloud', 'AWS',                 3),
  ('cicd',             'devops_cloud', 'CI / CD',             4)
ON CONFLICT (id) DO NOTHING;

-- ─── TYPESCRIPT ───────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('typescript', 'What is TypeScript and why use it over JavaScript?', 'TypeScript is a statically typed superset of JavaScript that compiles to plain JS. Benefits: compile-time type errors (catch bugs before running), better IDE autocomplete and refactoring, self-documenting code through types, safer large-scale codebases. TypeScript is a no-op at runtime — all type information is erased after compilation. Adopted by Google Angular, Airbnb, Slack, and most modern enterprise projects.', 1),
('typescript', 'What is the difference between interface and type alias?', 'interface: defines the shape of an object or class contract, can be extended with extends and merged (declaration merging). type alias: can represent primitives, unions, intersections, tuples — not just objects. Key rule: use interface for object shapes and public APIs (it can be extended); use type for unions, tuples, mapped types, and complex compositions. Both are equally valid for plain object shapes.', 2),
('typescript', 'What are generics in TypeScript?', 'Generics allow you to write reusable, type-safe functions, classes, and interfaces that work with multiple types. function identity<T>(arg: T): T { return arg; }. The T is a type parameter that gets filled in at the call site. Common examples: Array<T>, Promise<T>, React.FC<Props>. Constraints: function longest<T extends { length: number }>(a: T, b: T). Avoid using any when you need flexibility — use generics instead.', 3),
('typescript', 'What are union types and intersection types?', 'Union (|): value can be one of several types. type ID = string | number. Useful for nullable: string | null. Intersection (&): value must satisfy ALL types simultaneously. type AdminUser = User & { adminLevel: number }. Think of union as "OR" and intersection as "AND". Discriminated unions add a literal type field to distinguish members: type Shape = { kind: "circle"; radius: number } | { kind: "rect"; width: number }.', 4),
('typescript', 'What is the difference between any, unknown, and never?', 'any: opts out of type checking entirely — anything goes. Avoid it. unknown: type-safe counterpart of any — you must narrow/assert before using it. never: a type that has no values — functions that throw always, infinite loops, or exhaustive checks. Rule of thumb: use unknown when accepting input you will validate, never for impossible cases, and never use any except when wrapping untyped JS libraries.', 5),
('typescript', 'What are utility types in TypeScript?', 'Built-in generic types that transform existing types. Most common: Partial<T> (all props optional), Required<T> (all props required), Readonly<T> (no mutation), Pick<T, K> (subset of keys), Omit<T, K> (exclude keys), Record<K, V> (object type from key set), ReturnType<F> (return type of a function), Parameters<F> (parameter tuple of a function). These avoid writing duplicate type definitions manually.', 6),
('typescript', 'What is type narrowing / type guards?', 'Type narrowing is when TypeScript refines a broad type to a specific one inside a conditional branch. Built-in narrowing: typeof (for primitives), instanceof (for classes), in (for object properties), equality checks. Custom type guards: function isUser(x: any): x is User { return typeof x.name === "string"; }. Narrowing makes working with union types and discriminated unions safe and expressive.', 7),
('typescript', 'What is type assertion and when to use it?', 'Type assertion (as Type or <Type>) tells TypeScript to treat a value as a specific type, bypassing inference. const canvas = document.getElementById("c") as HTMLCanvasElement. Use only when you know more than TypeScript does — e.g., interacting with DOM APIs or JSON from external APIs. Never use as any to silence errors — that defeats the purpose. Double assertion (x as unknown as OtherType) is a last resort.', 8),
('typescript', 'What is the keyof and typeof operator?', 'keyof T: produces a union of all key names of type T. keyof User → "name" | "email" | "age". Used to write typed accessor functions: function get<T, K extends keyof T>(obj: T, key: K): T[K]. typeof x (at the type level): infers the type of a variable. const config = { port: 3000, host: "localhost" }; type Config = typeof config. Together they enable type-safe lookups without repeating yourself.', 9),
('typescript', 'What are conditional types?', 'Conditional types: T extends U ? X : Y. Evaluated at compile time based on whether T is assignable to U. Example: type IsArray<T> = T extends any[] ? true : false. Used heavily in utility types. With infer: type UnwrapPromise<T> = T extends Promise<infer R> ? R : T — extracts the resolved type from a Promise. Enables powerful type-level programming.', 10),
('typescript', 'What are enums in TypeScript?', 'Enums define a named set of constants. Numeric enum: enum Direction { Up = 0, Down, Left, Right }. String enum: enum Status { Active = "ACTIVE", Inactive = "INACTIVE" }. String enums are preferred — they are more debuggable. Const enums (const enum) are inlined at compile time (no runtime object). Downside of regular enums: they produce runtime JS objects; union types of literals are often a cleaner alternative: type Status = "active" | "inactive".', 11),
('typescript', 'What is strict mode in TypeScript and what does it enable?', 'strict: true in tsconfig.json enables a set of checks: strictNullChecks (string and string|null are different types), noImplicitAny (no implicit any), strictFunctionTypes (contravariant function params), strictPropertyInitialization (class properties must be initialized), and more. Always enable strict mode on new projects — it prevents the most common category of runtime null/undefined errors that TypeScript is designed to prevent.', 12);

-- ─── GIT ──────────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('git', 'What is Git and what problem does it solve?', 'Git is a distributed version control system that tracks changes to files over time. Every developer has a full copy of the history. Problems solved: parallel work without overwriting each other (branching), full history of every change (who changed what and why), ability to revert to any previous state, collaboration across teams globally. Created by Linus Torvalds in 2005 for the Linux kernel.', 1),
('git', 'What is the difference between git merge and git rebase?', 'merge: creates a merge commit that combines two branches — preserves the complete history, non-destructive. rebase: rewrites the commit history by replaying your commits on top of another branch — results in a linear history, no merge commit. Rule: never rebase public/shared branches (rewrites history others have). Use rebase for cleaning up local feature branches before merging; use merge for integrating into shared branches.', 2),
('git', 'What is the difference between git fetch and git pull?', 'git fetch: downloads remote commits, branches, and tags WITHOUT merging them into your working directory. Updates remote-tracking branches (origin/main). git pull: fetch + merge (or rebase if configured). git pull is essentially git fetch followed by git merge. Prefer fetch + review + merge to avoid surprise conflicts. Use git fetch --all to update all remote tracking branches.', 3),
('git', 'What is git stash?', 'git stash temporarily shelves uncommitted changes (both staged and unstaged) so you can switch branches or pull without committing unfinished work. git stash saves to a stack. git stash pop restores the latest stash and removes it. git stash list shows all stashes. git stash apply @{2} applies a specific stash without removing it. Use git stash push -m "message" to label stashes for clarity.', 4),
('git', 'What is git reset vs git revert?', 'git reset: moves the HEAD pointer (and optionally the index/working tree) to an earlier commit. Modes: --soft (keeps changes staged), --mixed (keeps changes unstaged, default), --hard (discards all changes). Rewrites history — dangerous on shared branches. git revert: creates a NEW commit that undoes a previous commit — history-safe, always the right choice for shared branches. Rule: reset for local cleanup, revert for shared history.', 5),
('git', 'What is a detached HEAD state?', 'Normally HEAD points to a branch name, which points to a commit. Detached HEAD means HEAD points directly to a commit hash (not a branch). This happens when you git checkout a specific commit, tag, or remote branch. Any commits made in detached HEAD are not on any branch and can be lost if you switch away. Fix: git checkout -b new-branch to save your work on a branch.', 6),
('git', 'What is git cherry-pick?', 'git cherry-pick <commit-hash> applies a specific commit from one branch to another, creating a new commit with the same changes. Useful for: applying a bug fix from a feature branch to main without merging the whole feature, or picking one commit from a colleague''s branch. Downside: duplicates commit history (both branches now have the same change). Use sparingly — it can create confusion about which branch has the fix.', 7),
('git', 'What is git bisect?', 'git bisect performs a binary search through git history to find the commit that introduced a bug. git bisect start → git bisect bad (current is broken) → git bisect good <hash> (last known good state) → Git checks out the midpoint → you test → git bisect good or bad → repeat. Git narrows down to the exact commit in O(log n) steps. Can be automated with a test script: git bisect run npm test.', 8),
('git', 'What is squashing commits and why do it?', 'Squashing combines multiple commits into one. Done with git rebase -i HEAD~N (interactive rebase) and marking commits as squash or fixup. Why: clean up messy "WIP" commit history before merging — one logical commit is easier to read, revert, and cherry-pick than 15 micro-commits. Some teams enforce "squash and merge" via GitHub/GitLab PR settings. Never squash commits that are already on shared branches.', 9),
('git', 'What are Git hooks?', 'Git hooks are scripts that run automatically on specific Git events. Client-side: pre-commit (run linting/tests before commit), commit-msg (validate commit message format), pre-push (run tests before push). Server-side: pre-receive (enforce policies on push). Stored in .git/hooks/. Tools like Husky make managing hooks easy in Node.js projects. Cannot be committed to the repo by default (only inside .git/), but husky stores them in package.json.', 10),
('git', 'What is the difference between Gitflow and trunk-based development?', 'Gitflow: main + develop + feature/release/hotfix branches. Formal release process. Good for versioned software with scheduled releases. Complex for fast-moving teams. Trunk-based development: everyone commits small, frequent changes to main (trunk) directly or via short-lived branches. Continuous deployment. Used by Google, Facebook, Netflix. Requires strong CI/CD and feature flags. Modern cloud-native teams prefer trunk-based — faster, simpler, fewer merge conflicts.', 11),
('git', 'What is a git tag and how does it differ from a branch?', 'A tag is a permanent pointer to a specific commit, typically used to mark release versions (v1.2.0). Unlike a branch, a tag does not move — it always points to the same commit. Lightweight tag: just a pointer. Annotated tag: includes metadata (tagger, date, message), can be signed. Best practice: annotate all release tags (git tag -a v1.0.0 -m "Release 1.0.0"). Tags must be explicitly pushed: git push origin --tags.', 12);

-- ─── DOCKER ───────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('docker', 'What is Docker and what problem does it solve?', 'Docker is a platform for building, shipping, and running applications in containers. Problem: "works on my machine" — applications behave differently across developer laptops, staging, and production because of different OS, library versions, and configs. Docker packages the app + all its dependencies into an isolated container that runs identically everywhere. Containers are faster to start than VMs and use less memory.', 1),
('docker', 'What is the difference between a Docker container and a VM?', 'VM: runs a full OS guest on top of a hypervisor (VMware, VirtualBox). Heavy: minutes to start, GBs of disk. Container: shares the host OS kernel, only contains the app and its dependencies. Lightweight: seconds to start, MBs of disk. Containers are not full isolation — they share the kernel. VMs provide stronger isolation. Use containers for packaging apps, VMs for running different OSes or strict security isolation.', 2),
('docker', 'What is a Dockerfile?', 'A Dockerfile is a text file with instructions to build a Docker image. Common instructions: FROM (base image), WORKDIR (set working directory), COPY / ADD (copy files), RUN (execute command during build), ENV (set env vars), EXPOSE (document port), CMD (default command when container starts), ENTRYPOINT (configure container as executable). Each instruction creates a layer. Layers are cached — put rarely-changing instructions (apt installs) before frequently-changing ones (COPY source code).', 3),
('docker', 'What is the difference between CMD and ENTRYPOINT in a Dockerfile?', 'ENTRYPOINT: defines the executable that always runs — cannot be easily overridden. CMD: provides default arguments to ENTRYPOINT, or a default command if no ENTRYPOINT. Both accept exec form ["node", "app.js"] (preferred) or shell form node app.js. Common pattern: ENTRYPOINT ["node"] CMD ["app.js"] — allows docker run myapp server.js to override just the argument. If you override CMD on docker run, ENTRYPOINT still runs.', 4),
('docker', 'What is the difference between COPY and ADD in Dockerfile?', 'COPY: simply copies files/directories from the build context into the container. Recommended for most cases — transparent and predictable. ADD: can copy files, extract .tar archives automatically, and fetch remote URLs (discouraged for URLs — use RUN curl instead). Best practice: always use COPY unless you specifically need tar extraction. ADD has unexpected behavior that makes Dockerfiles harder to reason about.', 5),
('docker', 'What is Docker Compose?', 'Docker Compose defines and runs multi-container applications using a docker-compose.yml file. Specify services (containers), networks, and volumes. docker compose up starts everything together. docker compose down stops and removes containers. Great for local development: define your app + database + Redis + message queue together. For production, Kubernetes is preferred over Compose. Compose V2 is integrated into Docker CLI (docker compose instead of docker-compose).', 6),
('docker', 'What are Docker volumes and why do you need them?', 'Container filesystems are ephemeral — data is lost when the container stops. Volumes persist data outside the container lifecycle. Types: named volumes (docker volume create mydata — managed by Docker, best for DBs), bind mounts (map a host directory into the container — best for development hot-reload), tmpfs mounts (in-memory, not persisted). Use volumes for databases, user uploads, logs. Do not store critical data inside a container layer.', 7),
('docker', 'What is Docker networking?', 'Docker provides virtual networks for container communication. Network types: bridge (default — containers on the same bridge can communicate by name), host (container uses host network, no isolation), overlay (for Docker Swarm/Kubernetes multi-host communication), none (no networking). docker network create mynet creates a custom network. Containers on the same named network can reach each other by service name (via Docker DNS). Expose ports to the host with -p 8080:80.', 8),
('docker', 'How do you optimize Docker image size?', 'Key techniques: (1) Use a slim/alpine base image (node:18-alpine vs node:18). (2) Multi-stage builds — build in one stage, copy only the artifact to a clean final stage. (3) Combine RUN commands with && to reduce layers. (4) Use .dockerignore to exclude node_modules, .git, test files. (5) Remove package manager caches after install (apt-get clean && rm -rf /var/lib/apt/lists/*). (6) Do not install dev dependencies in production stage.', 9),
('docker', 'What is a multi-stage Docker build?', 'Multi-stage builds use multiple FROM instructions in one Dockerfile. Each stage can use a different base image. You copy only what you need from one stage to the next. Example: Stage 1 (builder): use node:18 to install deps and compile TypeScript. Stage 2 (runtime): use node:18-alpine, copy only dist/ from builder. Result: final image has no build tools or source code — much smaller. Essential for compiled languages (Go, Java, TypeScript).', 10),
('docker', 'What is the difference between docker stop and docker kill?', 'docker stop: sends SIGTERM to the main process, giving it time to shutdown gracefully (default 10s timeout), then SIGKILL if still running. docker kill: sends SIGKILL immediately (or a specified signal) — no graceful shutdown. Always prefer docker stop to allow applications to flush data, close DB connections, finish in-flight requests. Use docker kill only when the container is unresponsive.', 11),
('docker', 'What is a Docker registry and Docker Hub?', 'A Docker registry is a server that stores and distributes Docker images. Docker Hub is the default public registry (docker.io). Images are referenced as registry/username/imagename:tag. Push: docker push myapp:v1. Pull: docker pull myapp:v1. Private registries: AWS ECR, Google GCR, GitHub Container Registry, self-hosted Harbor. In CI/CD: build → tag → push to registry → pull on server to deploy.', 12);

-- ─── KUBERNETES ───────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('kubernetes', 'What is Kubernetes and why use it?', 'Kubernetes (K8s) is an open-source container orchestration system. It automates: deployment, scaling, self-healing, load balancing, rolling updates, and rollbacks of containerized applications. Why use it: Docker Compose handles one host. Kubernetes manages hundreds of containers across many nodes. If a container crashes, K8s restarts it. If traffic spikes, K8s scales it. Originally built by Google, now CNCF. Steep learning curve but industry standard for production containers.', 1),
('kubernetes', 'What is a Pod in Kubernetes?', 'A Pod is the smallest deployable unit in K8s. It wraps one or more containers that share the same network namespace (same IP, ports) and storage volumes. Containers in a Pod communicate via localhost. Pods are ephemeral — if they crash, K8s creates a new one (new IP). You never create Pods directly in production — use a Deployment or StatefulSet that manages Pod lifecycle. Sidecar pattern: run a helper container (logger, proxy) alongside the main container in one Pod.', 2),
('kubernetes', 'What is the difference between a Deployment and a StatefulSet?', 'Deployment: manages stateless Pods. Pods are interchangeable — any Pod can be replaced with a new one. Supports rolling updates and rollbacks. Use for web servers, API services. StatefulSet: manages stateful applications (databases, message queues). Each Pod has a stable, unique network identity and persistent storage. Pods are created/deleted in order. Use for: PostgreSQL, Redis, Kafka, Zookeeper. Key difference: StatefulSet Pods have stable hostnames (pod-0, pod-1) and each has its own PersistentVolumeClaim.', 3),
('kubernetes', 'What is a Kubernetes Service?', 'A Service provides a stable IP and DNS name for a group of Pods (which come and go). Types: ClusterIP (default — only reachable within the cluster), NodePort (exposes on a static port on each node), LoadBalancer (creates a cloud load balancer, most common for public services), ExternalName (DNS alias to an external service). Services use label selectors to route to Pods. Pods are discovered by name: http://my-service:8080 within the cluster.', 4),
('kubernetes', 'What is a ConfigMap and a Secret in Kubernetes?', 'ConfigMap: stores non-sensitive configuration as key-value pairs, injected into Pods as env vars or mounted files. Secret: stores sensitive data (passwords, tokens, certs) — base64-encoded (not encrypted by default, but can be encrypted at rest). Both are consumed by Pods via env vars or volume mounts. Manage secrets with external tools in production: AWS Secrets Manager, HashiCorp Vault, or Kubernetes Sealed Secrets. Never commit Secrets to git.', 5),
('kubernetes', 'What is a Namespace in Kubernetes?', 'Namespaces provide logical separation within a cluster. You can have dev, staging, production namespaces in the same cluster, with resource quotas and network policies per namespace. Default namespaces: default (your workloads), kube-system (K8s internals), kube-public (publicly readable), kube-node-lease. Use namespaces to organize teams/environments. DNS within a cluster: service.namespace.svc.cluster.local. kubectl commands operate on the default namespace unless you pass -n.', 6),
('kubernetes', 'What is a Horizontal Pod Autoscaler (HPA)?', 'HPA automatically scales the number of Pod replicas based on observed CPU, memory, or custom metrics. Configured with min/max replicas and target metric threshold. Example: scale up when average CPU > 70%, scale down when < 30%. K8s checks metrics every 15 seconds by default. For the HPA to work, Pods must have resource requests set. Use with Cluster Autoscaler to also add/remove nodes when the cluster is full.', 7),
('kubernetes', 'What is a Kubernetes Ingress?', 'An Ingress is an API object that manages external HTTP/HTTPS access to services inside the cluster. It provides: host-based routing (api.example.com → api-service, app.example.com → web-service), path-based routing (/api → api-service, / → frontend), TLS termination. Requires an Ingress Controller (Nginx, Traefik, AWS ALB Ingress) to function. More flexible and cost-effective than creating one LoadBalancer Service per app.', 8),
('kubernetes', 'How do rolling updates and rollbacks work in Kubernetes?', 'Rolling update: gradually replaces old Pods with new ones. Controlled by maxUnavailable (max Pods offline at once) and maxSurge (max extra Pods during update). Zero downtime by default. kubectl rollout status deployment/myapp monitors progress. kubectl rollout undo deployment/myapp rolls back to the previous ReplicaSet. K8s keeps a configurable number of old ReplicaSets for rollback history (revisionHistoryLimit). Always set readiness probes so traffic only goes to healthy new Pods.', 9),
('kubernetes', 'What are PersistentVolumes and PersistentVolumeClaims?', 'PersistentVolume (PV): a piece of storage provisioned by an admin (or dynamically by a StorageClass). PersistentVolumeClaim (PVC): a request for storage by a user (size, access mode). K8s binds a PVC to a matching PV. Pods mount PVCs as volumes. StorageClass enables dynamic provisioning — requesting a 10Gi PVC automatically creates a 10Gi EBS volume on AWS. Access modes: ReadWriteOnce (one node), ReadOnlyMany, ReadWriteMany.', 10),
('kubernetes', 'What is Helm?', 'Helm is the package manager for Kubernetes. A Helm chart is a collection of YAML templates that define a K8s application. Instead of writing and managing 10 YAML files manually, you install a chart: helm install myrelease stable/postgresql. Charts are parameterized with values.yaml — customize without editing templates. Helm also handles upgrade, rollback, and uninstall. Used for: deploying community software (Prometheus, Grafana, cert-manager) and packaging your own services.', 11),
('kubernetes', 'What is the difference between liveness and readiness probes?', 'Readiness probe: determines if a Pod is ready to accept traffic. If it fails, K8s removes the Pod from Service endpoints (no traffic sent) but does NOT restart it. Use for: app still starting up, waiting for DB connection. Liveness probe: determines if a Pod is still alive. If it fails, K8s RESTARTS the Pod. Use for: detecting deadlocks, infinite loops, corrupted state. Always configure both. Do not make liveness probe depend on external services — that causes cascading restarts.', 12);

-- ─── AWS ──────────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('aws', 'What is AWS and what are its main service categories?', 'Amazon Web Services is the world''s largest cloud platform (33%+ market share). Core categories: Compute (EC2, Lambda, ECS, EKS), Storage (S3, EBS, EFS), Database (RDS, DynamoDB, ElastiCache), Networking (VPC, Route 53, CloudFront, API Gateway), Security (IAM, KMS, WAF), Developer Tools (CodePipeline, CodeBuild), AI/ML (SageMaker, Rekognition, Bedrock). AWS operates in Regions (geographic areas) and Availability Zones (isolated data centers within a region).', 1),
('aws', 'What is EC2 (Elastic Compute Cloud)?', 'EC2 provides virtual servers (instances) in the cloud. You choose instance type (CPU/RAM/GPU), OS AMI, storage (EBS), and network settings. Pricing models: On-Demand (pay per hour, most flexible), Reserved (1-3 year commitment, up to 72% cheaper), Spot (unused capacity, up to 90% cheaper but can be interrupted), Savings Plans. Key concepts: Security Groups (virtual firewall), Key Pairs (SSH access), AMIs (machine images), Auto Scaling Groups (scale based on load).', 2),
('aws', 'What is S3 (Simple Storage Service)?', 'S3 is object storage with virtually unlimited scale. Stores any file as an object (key = path, value = file) in buckets. 11 nines durability (99.999999999%). Storage classes: Standard (hot data), Infrequent Access, Glacier (archival, cents per GB/month). Key features: versioning (all versions stored), lifecycle policies (auto-archive/delete), static website hosting, pre-signed URLs (time-limited access), replication across regions, server-side encryption. Max object size: 5TB.', 3),
('aws', 'What is AWS Lambda?', 'Lambda is serverless compute — you upload code (function), AWS runs it on demand. You pay only for execution time (first 1M requests/month free). No servers to manage. Triggers: API Gateway (HTTP requests), S3 events, DynamoDB streams, SQS messages, EventBridge schedules. Cold start: first invocation takes longer as Lambda spins up a container. Limitations: 15-minute max execution, 10GB memory, 512MB-10GB ephemeral storage. Great for event-driven workloads, APIs with variable traffic, scheduled jobs.', 4),
('aws', 'What is IAM (Identity and Access Management)?', 'IAM controls WHO can do WHAT in your AWS account. Concepts: Users (individual people or apps with credentials), Groups (collection of users with shared permissions), Roles (identity assumed by services/EC2/Lambda — no long-term credentials), Policies (JSON documents that define allowed/denied actions on resources). Principle of least privilege: grant only what is needed. Never use root account for daily work. Use IAM roles for EC2/Lambda instead of hardcoded access keys. Enable MFA everywhere.', 5),
('aws', 'What is a VPC (Virtual Private Cloud)?', 'VPC is your private, isolated section of the AWS cloud. You define a CIDR block (10.0.0.0/16) and divide it into subnets. Public subnets: have a route to the Internet Gateway (for internet-facing resources). Private subnets: no direct internet access (for databases, internal services). NAT Gateway: lets private subnet resources make outbound internet requests without being reachable inbound. Security Groups (stateful — instance level) and NACLs (stateless — subnet level) control traffic.', 6),
('aws', 'What is the difference between RDS and DynamoDB?', 'RDS (Relational Database Service): managed MySQL, PostgreSQL, Oracle, SQL Server, Aurora. ACID transactions, SQL queries, complex joins. Vertically scalable primarily. Best for structured relational data. DynamoDB: managed NoSQL key-value/document database. Single-digit millisecond latency at any scale. Horizontally scalable automatically. Best for: gaming leaderboards, session stores, user profiles, IoT, anything needing massive throughput with simple access patterns. DynamoDB requires careful schema design upfront (access patterns determine your indexes).', 7),
('aws', 'What is the difference between SQS and SNS?', 'SQS (Simple Queue Service): message queue. Producer sends message to queue, consumer polls and processes it. One consumer processes each message. Decouples services, handles traffic spikes, retries on failure. Standard (at-least-once) or FIFO (exactly-once, ordered). SNS (Simple Notification Service): pub/sub. Publisher sends to topic, ALL subscribers receive it (fan-out). Subscribers: SQS queues, Lambda functions, HTTP endpoints, email. SNS → SQS pattern: fan out to multiple queues for parallel processing.', 8),
('aws', 'What is CloudFront?', 'CloudFront is AWS''s CDN (Content Delivery Network). It caches content at 450+ edge locations globally, reducing latency for users worldwide. Use for: static assets (S3 static site), API caching, video streaming. TTL controls how long content is cached at edges. Origin can be S3, ALB, EC2, API Gateway. Supports custom SSL certificates via ACM. Integrates with WAF for DDoS/SQL injection protection. cache-control headers from origin control CDN behavior. Invalidations (cost money) flush cached content.', 9),
('aws', 'What is the difference between vertical and horizontal scaling on AWS?', 'Vertical scaling: increase the size of one instance (t2.micro → t2.xlarge). Simple but limited by max instance size and requires downtime. Horizontal scaling: add more instances behind a load balancer. Elastic Load Balancer (ALB, NLB, CLB) distributes traffic. Auto Scaling Group (ASG) adds/removes instances based on CPU, requests, custom metrics. AWS architecture best practice: design for horizontal scaling from the start — stateless services, shared data in RDS/DynamoDB/ElastiCache, sessions in Redis.', 10),
('aws', 'What is ECS vs EKS?', 'ECS (Elastic Container Service): AWS-native container orchestration. Simpler to operate than K8s. Two launch types: EC2 (you manage the instances) or Fargate (fully serverless, no instance management). Great for: teams fully in AWS, simpler container workloads. EKS (Elastic Kubernetes Service): managed Kubernetes. Standard K8s API — portable to other clouds, rich ecosystem (Helm, Prometheus, etc.). More complex but industry standard. Use ECS for simple AWS-only workloads; EKS if your team knows K8s or you need portability.', 11),
('aws', 'What is the AWS shared responsibility model?', 'AWS is responsible for security OF the cloud (physical hardware, network infrastructure, hypervisor, managed service patching). You are responsible for security IN the cloud (OS patching on EC2, application code, data encryption, access control with IAM, network configuration). For managed services (RDS, Lambda), AWS manages more — you focus on application-level security. Knowing this model is critical for security architecture conversations in interviews.', 12);

-- ─── NEXT.JS ──────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('nextjs', 'What is Next.js and what problems does it solve over plain React?', 'Next.js is a React meta-framework by Vercel. It solves: routing (file-based, no react-router setup), server-side rendering for SEO and performance, static site generation, image optimization, API routes, code splitting, and TypeScript support out of the box. React is a UI library — Next.js is a complete production framework. Used by TikTok, Twitch, Hulu, and thousands of SaaS products.', 1),
('nextjs', 'What is SSR, SSG, and ISR in Next.js?', 'SSR (Server-Side Rendering): HTML generated on each request. Fresh data, slower TTFB. Use for: user-specific pages, frequently updated data. SSG (Static Site Generation): HTML generated at build time. Fastest possible delivery via CDN. Use for: blog posts, documentation, marketing pages. ISR (Incremental Static Regeneration): SSG pages regenerated in the background after a revalidation period. Combines static speed with fresh data — use for: e-commerce products, news articles (revalidate: 60 seconds).', 2),
('nextjs', 'What is the difference between the App Router and Pages Router?', 'Pages Router (pre-Next.js 13): pages/ directory, getServerSideProps/getStaticProps, client-side by default. App Router (Next.js 13+): app/ directory, React Server Components by default, nested layouts, streaming, server actions. App Router is the future — it co-locates components, layouts, loading states, error boundaries, and data fetching in one folder. Pages Router still works and is appropriate for existing apps.', 3),
('nextjs', 'What are React Server Components (RSC)?', 'Server Components run only on the server — they have no client-side JS bundle. They can: access databases directly, read env vars, use async/await. They cannot: use useState, useEffect, event handlers, or browser APIs. Client Components (with "use client" directive) have full React interactivity. Default in App Router: all components are Server Components unless marked "use client". This enables zero-JS components and much smaller bundles.', 4),
('nextjs', 'What is getServerSideProps?', 'getServerSideProps (Pages Router only): runs on the server on every request, passes data as props to the page component. Used when you need: auth-protected pages, frequently updated data, request-specific data (cookies, headers). Slower than SSG because it runs per-request. In App Router: replace it with async Server Components that fetch data directly.', 5),
('nextjs', 'What is getStaticProps and getStaticPaths?', 'getStaticProps: fetches data at build time, feeds it to a static page. getStaticPaths: for dynamic routes ([slug].tsx), defines which paths to pre-build. fallback: false (404 for unlisted paths), true (generate on first request), blocking (SSR for unlisted paths until generated). In App Router: replaced by async Server Components with revalidation: { revalidate: 60 } in fetch options.', 6),
('nextjs', 'How does Next.js handle images?', 'The next/image component automatically: optimizes images (WebP/AVIF conversion), lazy loads by default, prevents layout shift (requires width/height or fill), serves appropriately sized images for different viewports. Images are processed on-demand by a serverless function and cached. For static exports or external images, configure remotePatterns in next.config.js. Always use next/image over plain img for performance.', 7),
('nextjs', 'What are API Routes in Next.js?', 'API Routes (pages/api/*.ts) create serverless API endpoints within the Next.js app. Each file exports a handler(req, res) function. Used for: form submissions, webhooks, BFF (Backend for Frontend) proxy. In App Router: Route Handlers (app/api/*/route.ts) replace API Routes — export named functions GET, POST, PUT, DELETE. Great for apps that don''t want a separate backend. Not suitable for long-running processes — use serverless-compatible patterns.', 8),
('nextjs', 'What is middleware in Next.js?', 'Middleware (middleware.ts at root) runs before a request is completed — at the edge, before the server processes it. Use cases: authentication (check token, redirect to /login), A/B testing (rewrite to different page variant), geolocation-based redirects, rate limiting. Runs on Vercel Edge Runtime (no Node.js APIs, only Web APIs). Much faster than server-side checks since it runs at CDN edge. Returns NextResponse.next(), redirect(), rewrite(), or json().', 9),
('nextjs', 'How does file-based routing work in Next.js?', 'In Pages Router: files in pages/ map to routes. pages/about.tsx → /about. pages/blog/[slug].tsx → /blog/any-slug. pages/index.tsx → /. In App Router: folders in app/ define routes. app/blog/[slug]/page.tsx → /blog/any-slug. Layouts: app/layout.tsx wraps all children. Nested layouts: app/blog/layout.tsx wraps all blog pages. Special files: page.tsx (route UI), layout.tsx (persistent UI), loading.tsx (Suspense boundary), error.tsx (error boundary), not-found.tsx.', 10);

-- ─── GRAPHQL ──────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('graphql', 'What is GraphQL and how does it differ from REST?', 'GraphQL is a query language for APIs and a runtime to execute those queries. Difference from REST: REST has multiple endpoints per resource (GET /users, GET /users/:id/posts). GraphQL has a single endpoint and clients request exactly the data they need — no over-fetching (getting too much) or under-fetching (needing multiple requests). Developed by Facebook in 2012, open-sourced in 2015. Used by GitHub, Twitter, Shopify, and many large APIs.', 1),
('graphql', 'What is a GraphQL schema?', 'The schema is a contract between client and server — it defines all types, queries, mutations, and subscriptions. Written in SDL (Schema Definition Language). Scalar types: Int, Float, String, Boolean, ID. Custom types: type User { id: ID!, name: String!, email: String! }. The schema is the single source of truth for the API shape. The ! means non-nullable. Clients can explore the schema via introspection and tools like GraphiQL or Apollo Sandbox.', 2),
('graphql', 'What is the difference between queries, mutations, and subscriptions?', 'Query: read data (equivalent to GET). Mutation: write/change data (equivalent to POST/PUT/DELETE). Subscription: real-time data via WebSocket — server pushes updates to client when data changes (e.g., chat messages, live scores). All are declared in the schema and executed against the single /graphql endpoint. Most apps only use queries and mutations. Subscriptions require WebSocket infrastructure and are only needed for true real-time features.', 3),
('graphql', 'What is a resolver in GraphQL?', 'A resolver is a function on the server that returns data for a specific field in the schema. Every field in a GraphQL query is resolved by a resolver function. Signature: resolver(parent, args, context, info). parent = return value of the parent resolver. args = arguments passed in the query. context = shared request data (auth user, DB connection). info = query metadata. The resolver chain starts at the root (Query/Mutation) and walks down the tree.', 4),
('graphql', 'What is the N+1 problem in GraphQL and how do you solve it?', 'N+1 problem: fetching a list of N users, then making a separate DB query for each user''s posts = N+1 DB queries total. This happens because each Post resolver fires independently. Solution: DataLoader (by Facebook). DataLoader batches multiple individual loads into a single DB query per tick of the event loop. Instead of N queries, you get 1 batch query. Create a DataLoader per request (not global) to avoid cross-request data leaking in context.', 5),
('graphql', 'What are GraphQL fragments?', 'Fragments are reusable units of a query — they describe a set of fields on a type. Avoid repeating the same field list across multiple queries. Defined with fragment UserFields on User { id name email }. Used in queries with the spread operator: ...UserFields. In Apollo Client, fragments are central to the co-location pattern — each UI component defines and uses its own fragment, assembled into larger queries.', 6),
('graphql', 'What is Apollo Client and Apollo Server?', 'Apollo Server: popular Node.js GraphQL server. Define schema + resolvers, Apollo handles the HTTP endpoint, schema validation, and introspection. Apollo Client: state management and data fetching library for the frontend. Handles caching (normalized InMemoryCache), loading/error states, mutations, refetching, subscriptions, and optimistic UI updates. Together they form the most popular GraphQL stack. Alternatives: graphql-yoga (server), urql (client).', 7),
('graphql', 'What are directives in GraphQL?', 'Directives annotate schema or query fields to modify behavior. Built-in: @include(if: Boolean) and @skip(if: Boolean) for conditional field inclusion in queries. @deprecated(reason: String) on schema fields to mark them obsolete. Custom server-side directives: @auth (check permissions), @rateLimit, @cacheControl. Defined in schema with directive @myDirective on FIELD_DEFINITION. Powerful for cross-cutting concerns like authorization.', 8),
('graphql', 'What is GraphQL introspection?', 'Introspection lets clients query the schema itself — discover all available types, queries, mutations, and fields at runtime. Used by developer tools: GraphiQL, Apollo Sandbox, Insomnia. The __schema and __type meta-fields are always available. Disable introspection in production for security — it reveals your entire API structure to potential attackers. Use schema registry or private docs instead of introspection for production clients.', 9),
('graphql', 'When would you choose GraphQL over REST?', 'Choose GraphQL when: multiple clients (mobile, web, partner APIs) need different shapes of the same data, you have complex nested/relational data structures, your frontend teams need to iterate without backend changes, or you need to aggregate multiple backend services (API gateway pattern). Stick with REST when: the API is simple (CRUD on a few resources), you need strong HTTP caching (GET cache), teams are small and co-located, or you''re building a public API (REST is more widely understood).', 10);

-- ─── POSTGRESQL ───────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('postgresql', 'What makes PostgreSQL different from other databases?', 'PostgreSQL is a fully ACID-compliant, open-source ORDBMS (Object-Relational). Distinguishing features: JSONB (binary JSON with indexing), advanced indexing (GiST, GIN, BRIN, partial), window functions, CTEs (WITH queries), table inheritance, full-text search, extensive extension system (PostGIS for geospatial, TimescaleDB for time-series, pg_vector for AI embeddings). Often called "the most advanced open-source database". Preferred over MySQL for complex queries and data integrity.', 1),
('postgresql', 'What are window functions in PostgreSQL?', 'Window functions compute a result across a set of rows related to the current row, without collapsing them (unlike GROUP BY). Syntax: function() OVER (PARTITION BY col ORDER BY col). Common: ROW_NUMBER() (unique row number per partition), RANK() / DENSE_RANK(), LAG/LEAD (access previous/next row), SUM/AVG (running totals). Example: SELECT name, salary, RANK() OVER (PARTITION BY dept ORDER BY salary DESC) FROM employees — ranks employees within each department.', 2),
('postgresql', 'What is a CTE (Common Table Expression)?', 'CTE is a named temporary result set defined with WITH. Makes complex queries readable by breaking them into named steps. WITH active_users AS (SELECT * FROM users WHERE active=true), revenue AS (SELECT user_id, SUM(amount) FROM orders GROUP BY user_id) SELECT u.name, r.revenue FROM active_users u JOIN revenue r ON u.id=r.user_id. Recursive CTEs (WITH RECURSIVE) traverse hierarchical data like org charts and category trees.', 3),
('postgresql', 'What is JSONB in PostgreSQL?', 'JSONB stores JSON as decomposed binary — faster to query than JSON (text). Supports GIN indexes for key/value lookups. Operators: -> (get by key, returns JSON), ->> (get by key, returns text), #> (path access), @> (containment: does this JSON contain that?), ? (key exists). Allows indexing specific JSON fields: CREATE INDEX ON orders ((data ->> ''status'')). Use JSONB for semi-structured data where schema might vary, but do not store relational data as JSON.', 4),
('postgresql', 'What are triggers in PostgreSQL?', 'A trigger is a function that automatically fires on INSERT, UPDATE, or DELETE events on a table. BEFORE triggers can modify/cancel the operation. AFTER triggers fire after the operation. ROW-level (once per affected row) vs STATEMENT-level (once per SQL statement). Use cases: audit logs (record who changed what), enforcing complex constraints, auto-updating timestamps (updated_at), replicating changes to another table. Overuse of triggers makes debugging hard — prefer application logic when possible.', 5),
('postgresql', 'What is EXPLAIN ANALYZE in PostgreSQL?', 'EXPLAIN shows the query execution plan (which indexes, join types, estimated costs). EXPLAIN ANALYZE actually executes the query and shows actual vs estimated rows and timing. Key things to look for: Seq Scan on large tables (needs an index), Nested Loop with many rows (consider Hash Join), high actual vs estimated rows (run ANALYZE to update statistics), slow Sort steps (can be eliminated with an index on the ORDER BY column). Always EXPLAIN ANALYZE slow queries before optimizing.', 6),
('postgresql', 'What is VACUUM in PostgreSQL?', 'PostgreSQL uses MVCC (Multi-Version Concurrency Control) — updates create new row versions, old versions are marked as dead but not immediately removed. VACUUM reclaims space from dead row versions. AUTOVACUUM runs automatically. VACUUM FULL rewrites the entire table (acquires exclusive lock — avoid on busy tables). ANALYZE updates statistics used by the query planner. Run VACUUM ANALYZE after bulk inserts/deletes. Bloat (dead rows not cleaned up) slows queries and wastes disk.', 7),
('postgresql', 'What are partial and expression indexes?', 'Partial index: includes only rows matching a WHERE condition. CREATE INDEX idx_active ON users(email) WHERE active=true. Smaller index, faster for queries with that same condition. Expression index: indexes the result of an expression. CREATE INDEX idx_lower_email ON users(lower(email)). Queries using WHERE lower(email) = ''...'' will use this index. Both reduce index size and maintenance overhead compared to full indexes. Use when you frequently query a subset of rows or expressions.', 8),
('postgresql', 'What is point-in-time recovery (PITR) in PostgreSQL?', 'PITR lets you restore a database to any specific moment in the past, not just the last backup. Requires: base backups (full dumps periodically) + continuous WAL (Write-Ahead Log) archiving. The WAL records every change — replaying it from a base backup forward recovers to any timestamp. Used by: AWS RDS (35-day PITR window), managed PostgreSQL services. Critical for disaster recovery. Test your PITR process regularly — you don''t want to discover it''s broken during an outage.', 9),
('postgresql', 'What are sequences and SERIAL in PostgreSQL?', 'A sequence is an auto-incrementing counter object. SERIAL is shorthand for CREATE SEQUENCE + DEFAULT nextval(). BIGSERIAL for large tables. PostgreSQL 10+ adds GENERATED ALWAYS AS IDENTITY (SQL standard alternative to SERIAL, preferred). Sequences are not rolled back on transaction failure — gaps in IDs are normal and expected. Use UUID (gen_random_uuid()) for distributed systems where multiple nodes insert concurrently. UUIDs are globally unique with no coordination needed.', 10);

-- ─── REDIS ────────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('redis', 'What is Redis and when should you use it?', 'Redis (Remote Dictionary Server) is an in-memory data store used as a cache, message broker, and session store. Data lives in RAM → microsecond read/write latency. Use for: caching expensive DB queries, session/JWT storage, rate limiting counters, pub/sub messaging, distributed locks, leaderboards, queue (with Lists). Not suitable for: primary data store (memory is expensive, limited), complex relational queries, data larger than RAM. Persist with RDB snapshots or AOF logging.', 1),
('redis', 'What are the main data structures in Redis?', 'String: any binary data, counters (INCR), cached JSON. List: ordered collection of strings, FIFO queue (LPUSH/RPOP), LIFO stack. Hash: map of field → value (store objects without serialization). Set: unique unsorted strings (membership check, intersections). Sorted Set (ZSet): unique members with a float score, sorted by score (leaderboards, time-series). HyperLogLog: approximate cardinality (count unique visitors at scale). Bitmap: bit-level operations. Stream: append-only log (like Kafka-lite).', 2),
('redis', 'What is the difference between RDB and AOF persistence?', 'RDB (Redis Database): point-in-time snapshots saved to disk at intervals (e.g., every 5 minutes). Compact, fast restart, but can lose up to 5 minutes of data on crash. AOF (Append-Only File): logs every write command. Can be synced every second (lose 1s data) or every command (safest, slowest). File grows large — Redis rewrites/compresses it periodically. Production recommendation: enable both. RDB for fast restarts; AOF for minimal data loss. Redis 7+ has RDB-AOF hybrid.', 3),
('redis', 'What is TTL and how does Redis handle expiry?', 'TTL (Time To Live): SET key value EX 3600 sets a 1-hour expiry. EXPIRE key 300 sets expiry on existing key. TTL key returns remaining seconds (-1 = no expiry, -2 = key does not exist). Redis uses lazy expiry (check on access) + periodic active expiry (sample random keys every 100ms). Expired keys are not immediately removed from memory — they are cleaned up lazily. For memory management, configure maxmemory with an eviction policy (LRU, LFU, etc.).', 4),
('redis', 'What is Redis Pub/Sub?', 'Pub/Sub allows message broadcasting. Publisher: PUBLISH channel message. Subscriber: SUBSCRIBE channel (blocks, receives all messages on the channel). No message persistence — if no subscriber is listening, the message is lost. Use for: real-time notifications, chat, live dashboards. For durability, use Redis Streams instead (like Kafka — messages are stored and consumers can replay from any offset). Redis Pub/Sub is fire-and-forget; Redis Streams are durable.', 5),
('redis', 'What is the difference between Redis Sentinel and Redis Cluster?', 'Redis Sentinel: high availability for a single Redis instance. Monitors master/replica nodes, automatically promotes a replica if master fails (failover). For client-side: query Sentinel for the current master address. Handles failover but does NOT shard data. Redis Cluster: distributed sharding across multiple nodes + high availability. Data is split into 16,384 hash slots distributed across nodes. Each node handles a subset of keys. Use Sentinel when you need HA for one dataset; Cluster when dataset exceeds one node''s RAM.', 6),
('redis', 'How do you implement a rate limiter with Redis?', 'Fixed window: INCR user:123:2024010112 (key = user+hour). EXPIRE to 3600. If value > limit, reject. Sliding window log: store request timestamps in a Sorted Set. ZADD + ZREMRANGEBYSCORE (remove old) + ZCARD (count). Token bucket: atomic Lua script that checks and decrements a counter. Leaky bucket: use a List as a queue. Redis is ideal for rate limiting because INCR is atomic and fast. Popular libraries (Express rate-limit, ioredis-rate-limiter) implement these patterns.', 7),
('redis', 'What are Redis transactions (MULTI/EXEC)?', 'MULTI starts a transaction block. Commands after MULTI are queued, not executed. EXEC runs all queued commands atomically (all or nothing at the command level). DISCARD cancels the queue. Important: Redis transactions do NOT roll back on runtime errors (only syntax errors before EXEC prevent execution). WATCH implements optimistic locking: watch a key, if it changes before EXEC, the transaction aborts. For complex atomic operations, use Lua scripts (EVAL) — they run atomically and cannot be interrupted.', 8),
('redis', 'What is Redis pipelining?', 'Pipelining sends multiple commands to Redis without waiting for each reply — reduces round-trip latency. Instead of 100 separate network round-trips, send 100 commands in one batch. The client buffers commands; Redis processes them sequentially and sends all replies at once. Different from transactions: pipelining is about network efficiency, not atomicity. Most Redis clients (ioredis, Jedis) support pipelines. Use for bulk inserts, bulk reads, or any scenario with many sequential Redis commands.', 9),
('redis', 'What is the difference between Redis and Memcached?', 'Both are in-memory caches. Memcached: simpler, multi-threaded (better CPU utilization for pure caching), only strings, no persistence, no pub/sub, no Lua scripting. Redis: single-threaded (but very fast), rich data structures, persistence, pub/sub, Lua scripts, cluster mode, Streams. Choose Redis unless you specifically need Memcached''s multi-threading for pure caching workloads. Redis is the default choice for new projects due to its versatility.', 10);

-- ─── REACT NATIVE ─────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('react_native', 'What is React Native and how does it differ from React?', 'React Native lets you build native iOS and Android apps using React and JavaScript. Instead of rendering to the browser DOM, it renders to native platform components (UIView on iOS, android.view on Android). Difference: React uses HTML elements (div, span), React Native uses native components (View, Text, Image, TouchableOpacity). CSS is replaced by StyleSheet.create with a subset of flexbox. Code is shared across platforms; platform-specific code uses Platform.OS.', 1),
('react_native', 'What is the React Native bridge architecture?', 'The original architecture: JavaScript thread (your code) and Native thread communicate over a bridge. Bridge is asynchronous and serializes data as JSON strings passed between threads. Limitation: the serialization/deserialization overhead and async nature causes jank on complex animations. This is why very complex interactions could feel sluggish. The New Architecture (JSI) replaces the bridge with a direct C++ interface between JS and native code — synchronous, no serialization.', 2),
('react_native', 'What is the New Architecture in React Native (JSI/Fabric)?', 'New Architecture (fully available RN 0.73+): JSI (JavaScript Interface): replaces the bridge with direct C++ bindings — JS calls native synchronously, no JSON serialization. Fabric: new rendering system — components render on the main thread, enabling synchronous layout events. TurboModules: native modules loaded lazily and accessed synchronously via JSI. Together: smoother animations, fewer jank issues, better interop. Expo SDK 50+ supports New Architecture.', 3),
('react_native', 'What is the difference between FlatList and ScrollView?', 'ScrollView: renders ALL children at once — simple, good for small fixed lists or forms. FlatList: virtualized list — only renders items visible on screen + a small buffer. Recycles components as you scroll. Use FlatList for any list of unknown or large length (50+ items). Key props: data, renderItem, keyExtractor, onEndReached (infinite scroll), refreshControl (pull to refresh), ListHeaderComponent, ListEmptyComponent. SectionList for grouped/categorized lists.', 4),
('react_native', 'How does navigation work in React Native?', 'React Navigation is the standard library. Core navigators: Stack (push/pop screens), Tab (bottom/top tabs), Drawer (side menu). Nested navigators for complex apps (Tab inside Stack). Navigation prop: navigation.navigate("Screen"), navigation.goBack(), navigation.push(), navigation.replace(). Route params: navigation.navigate("Detail", { id: 42 }) — received via route.params.id. Deep linking: map URLs to screens. SafeAreaProvider handles notch/bottom bar safe areas.', 5),
('react_native', 'What is Expo vs bare React Native?', 'Expo: managed workflow with pre-built native modules, easy setup, Expo Go for quick testing, EAS Build for production APK/IPA. Trade-off: limited to Expo SDK''s native modules. Expo bare workflow (or bare RN): full access to native code, can write custom Java/Kotlin/Swift modules, more complex setup. Recommendation: start with Expo managed — it covers 95% of use cases. Eject to bare only if you need a native module Expo doesn''t support.', 6),
('react_native', 'How do you handle platform differences in React Native?', 'Platform.OS: returns "ios" or "android" — use for conditional logic. Platform.select(): picks from an object based on OS. Platform-specific files: Button.ios.tsx and Button.android.tsx — RN automatically picks the right file. StyleSheet differences: elevation (Android shadow), shadow* props (iOS shadow). Status bar: StatusBar component with different defaults per OS. Keyboard behavior: KeyboardAvoidingView with behavior="padding" (iOS) vs "height" (Android).', 7),
('react_native', 'What are common performance optimizations in React Native?', 'Use FlatList (not ScrollView) for long lists. Memoize components with React.memo and callbacks with useCallback. Use InteractionManager.runAfterInteractions for post-navigation work. Move heavy computations to the background with Hermes (JS engine) or native modules. Avoid anonymous functions in JSX (creates new references every render). Use Reanimated 2 for 60fps animations that run on the UI thread, not JS thread. Profile with Flipper or Hermes profiler.', 8),
('react_native', 'What is the Hermes JavaScript engine?', 'Hermes is a JS engine built by Meta specifically for React Native. Benefits vs V8/JavaScriptCore: smaller app size (bytecode pre-compiled at build time), faster app startup time (no JIT warmup), lower memory usage. Default in RN 0.70+ and Expo SDK 47+. Hermes compiles your JS to bytecode during the build — the device doesn''t need to parse/compile JS on startup. Downside: some advanced JS features may behave slightly differently. Always test with Hermes enabled.', 9),
('react_native', 'How do you store data locally in React Native?', 'AsyncStorage: simple key-value string store (deprecated in core, use @react-native-async-storage/async-storage). Expo SecureStore: encrypted storage for sensitive data (tokens, keys) — limited to 2KB per value. MMKV: fast synchronous key-value storage backed by a C++ implementation (react-native-mmkv — 30x faster than AsyncStorage). SQLite: relational DB via expo-sqlite for complex structured data. Realm: object database by MongoDB, good for offline-first apps.', 10);

-- ─── SPRING BOOT ──────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('spring_boot', 'What is Spring Boot and how is it different from Spring Framework?', 'Spring Framework is a comprehensive Java framework for building enterprise apps (IoC, AOP, MVC, data access). Spring Boot is an opinionated layer on top of Spring that eliminates boilerplate configuration. Auto-configuration: Spring Boot detects classpath dependencies and configures them automatically. Embedded server: runs Tomcat/Jetty directly — no WAR deployment needed. Starter dependencies bundle related libraries. Spring Boot lets you go from zero to a running REST API in minutes vs hours with plain Spring.', 1),
('spring_boot', 'What is dependency injection (DI) in Spring?', 'DI is a design pattern where objects receive their dependencies from an external source rather than creating them. Spring''s IoC container creates and manages beans (objects). Inject via constructor (preferred), setter, or field (@Autowired). Constructor injection is best: dependencies are explicit, immutable, and easy to test (just pass mocks). Avoid field injection (@Autowired on a field) — it hides dependencies and makes unit testing harder.', 2),
('spring_boot', 'What are Spring Boot annotations?', '@SpringBootApplication: main class, enables auto-configuration + component scan. @RestController: marks a class as a REST controller (combines @Controller + @ResponseBody). @GetMapping/@PostMapping: maps HTTP verbs to methods. @Service: business logic layer. @Repository: data access layer (also translates DB exceptions). @Component: generic Spring-managed bean. @Autowired: injects a dependency. @Value: injects a property value. @Transactional: wraps method in a DB transaction.', 3),
('spring_boot', 'What is Spring Data JPA?', 'Spring Data JPA simplifies database access by generating SQL from method names. Extend JpaRepository<User, Long> and get CRUD methods free. Define custom queries by method name: findByEmailAndActive(email, true) → SELECT * FROM users WHERE email=? AND active=?. @Query for complex queries. @Transactional for transaction management. Works with Hibernate as the JPA implementation. Entities marked with @Entity, primary keys with @Id and @GeneratedValue.', 4),
('spring_boot', 'What is application.properties vs application.yml?', 'Both configure Spring Boot properties. application.properties: key=value format, one property per line. application.yml: YAML format, hierarchical with indentation. Same values — just different syntax. Profiles: application-dev.properties, application-prod.yml activated by spring.profiles.active. Best practice: use profiles for environment-specific config (DB URL, API keys), never hardcode secrets — use environment variables or Spring Cloud Config/HashiCorp Vault.', 5),
('spring_boot', 'What is Spring Security?', 'Spring Security handles authentication (who are you?) and authorization (what can you do?). Security filter chain intercepts all requests. Configure with SecurityFilterChain bean. HTTP Basic, Form Login, OAuth2, JWT are all supported. Method-level security: @PreAuthorize("hasRole(''ADMIN'')"). CSRF protection enabled by default (disable for REST APIs). Configure which endpoints are public vs protected with requestMatchers. JWT implementation: validate token in OncePerRequestFilter, set SecurityContext.', 6),
('spring_boot', 'What is the difference between @Controller and @RestController?', '@Controller: returns view names (for Thymeleaf/JSP server-side rendering). Methods return String (view name) or ModelAndView. To return JSON from a @Controller method, add @ResponseBody. @RestController: shorthand for @Controller + @ResponseBody — all methods return JSON/XML serialized from the return object. For REST APIs, always use @RestController. @RequestBody deserializes the request body into a Java object.', 7),
('spring_boot', 'What is Spring Boot Actuator?', 'Actuator exposes production-ready endpoints for monitoring and management. Built-in endpoints: /actuator/health (is the app up?), /actuator/metrics (JVM, request counts, latency), /actuator/env (config properties), /actuator/info, /actuator/loggers. Integrates with Micrometer for exporting metrics to Prometheus, Grafana, Datadog. Secure actuator endpoints in production (only expose health publicly, require auth for the rest). Add spring-boot-starter-actuator to pom.xml.', 8),
('spring_boot', 'What is the Spring Bean lifecycle?', 'Lifecycle: IoC container instantiates the bean → injects dependencies → calls @PostConstruct method (initialization) → bean is in use → @PreDestroy called on shutdown → bean is destroyed. Custom initialization/destruction: implement InitializingBean/DisposableBean, or use init-method/destroy-method attributes. Bean scopes: singleton (default — one instance per container), prototype (new instance per request), request (one per HTTP request), session (one per HTTP session).', 9),
('spring_boot', 'What is @Transactional in Spring?', '@Transactional wraps a method in a database transaction — if the method throws an unchecked exception (RuntimeException or Error), the transaction rolls back; otherwise it commits. Propagation: REQUIRED (join existing or create new), REQUIRES_NEW (always new, suspends existing), NESTED. Isolation: READ_COMMITTED, REPEATABLE_READ, etc. Common mistake: calling a @Transactional method from within the same class — Spring AOP proxy is bypassed, transaction does not work. Always call from another bean.', 10);

-- ─── DJANGO ───────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('django_python', 'What is Django and what is its MTV architecture?', 'Django is a high-level Python web framework following MTV: Model (data layer + ORM), Template (presentation, though DRF replaces this for APIs), View (business logic, equivalent to MVC''s controller). Django''s "batteries included" philosophy: built-in admin, authentication, ORM, forms, CSRF protection, internationalization. Compared to Flask: Django is more opinionated and feature-complete; Flask is minimal and flexible. Django is used by Instagram, Disqus, Pinterest, Spotify.', 1),
('django_python', 'What is the Django ORM?', 'Django''s ORM maps Python classes (models) to database tables. Define fields with field types: CharField, IntegerField, ForeignKey, ManyToManyField. QuerySets are lazy — no DB hit until evaluated. Common operations: User.objects.filter(active=True).order_by("-created_at")[:10]. select_related() for ForeignKey (JOIN), prefetch_related() for ManyToMany (separate query). Use only() or values() to select specific fields and avoid over-fetching. Generate migrations: makemigrations → migrate.', 2),
('django_python', 'What are Django migrations?', 'Migrations track changes to your models over time and apply them to the database. python manage.py makemigrations generates migration files from model changes. python manage.py migrate applies them. Migrations should be committed to git. Common pitfalls: renaming fields (Django can''t detect renames, will DROP and CREATE), circular dependencies between apps. squashmigrations compresses history. RunPython allows custom Python logic in migrations. Never edit existing migration files once applied to production.', 3),
('django_python', 'What is Django REST Framework (DRF)?', 'DRF is the standard library for building REST APIs with Django. Key components: Serializer (validates input + serializes output), ViewSet (groups CRUD operations), Router (auto-generates URL patterns), Authentication (Token, Session, JWT), Permissions (IsAuthenticated, IsAdminUser, custom). ModelSerializer generates fields from a model automatically. APIView for full control; Generic views (ListCreateAPIView) for common patterns. Browsable API makes development easy.', 4),
('django_python', 'What is the difference between ForeignKey, ManyToManyField, and OneToOneField?', 'ForeignKey (many-to-one): many Posts belong to one User. Creates a column in the child table. OneToOneField: one Profile belongs to one User — like ForeignKey with unique=True. Used to extend a model. ManyToManyField: many Students enroll in many Courses. Django creates a junction table automatically. Use through= to customize the junction table (e.g., add an enrollment date). Access related objects: user.post_set.all() or define related_name for a cleaner API.', 5),
('django_python', 'What is Django middleware?', 'Middleware is a hook into Django''s request/response processing. Each middleware is a class with process_request (before view) and process_response (after view) methods. Built-in middleware: SecurityMiddleware (HTTPS redirect, HSTS), SessionMiddleware, CsrfViewMiddleware, AuthenticationMiddleware. Order matters: listed top to bottom in settings.MIDDLEWARE. Custom middleware for: logging, rate limiting, setting request context (current user, tenant ID). Keep middleware lightweight — it runs for every request.', 6),
('django_python', 'What is Django''s caching framework?', 'Django supports multiple cache backends: in-memory (local dev), memcached, Redis (most common in production). Cache the entire view with @cache_page(60*15) (15-minute cache). Low-level API: cache.set("key", value, 300), cache.get("key"). Template fragment caching with {% cache 500 sidebar %}. Per-site cache caches everything. Use Redis via django-redis. Cache invalidation is the hard part: use meaningful keys, set appropriate TTLs, and clear related caches when data changes.', 7),
('django_python', 'What is Celery and how does it integrate with Django?', 'Celery is a distributed task queue for running background/async jobs. Common uses: sending emails, resizing images, generating reports, calling third-party APIs. Django → Celery → Redis/RabbitMQ (broker) → Worker processes. Define tasks with @shared_task. Call asynchronously: my_task.delay(args) or with ETA: my_task.apply_async(countdown=60). Celery Beat schedules periodic tasks. Monitor with Flower. Essential for any Django app that does non-trivial background processing.', 8),
('django_python', 'What is the Django admin?', 'Django admin is an auto-generated CRUD interface for your models — enable with admin.site.register(MyModel). Customize with ModelAdmin: list_display, list_filter, search_fields, ordering, readonly_fields, inline models. Access at /admin/ (create superuser first). Useful for: content management, data verification, support tools. Do NOT use admin as the primary user-facing UI — it lacks authentication customization and can be a security risk if not properly secured. Protect it: change the URL, add 2FA, restrict by IP.', 9),
('django_python', 'What is signals in Django?', 'Signals allow decoupled components to get notified when certain actions occur. Common signals: post_save (after object saved), pre_delete, user_logged_in. Connect a receiver: @receiver(post_save, sender=User) def on_user_created(sender, instance, created, **kwargs). Useful for: sending a welcome email when user registers, creating a Profile when User is created, invalidating cache on object save. Overuse of signals makes code hard to trace — prefer explicit calls in views/serializers when possible.', 10);

-- ─── CI/CD ────────────────────────────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('cicd', 'What is CI/CD?', 'CI (Continuous Integration): developers frequently merge code to a shared branch; automated tests run on every push to catch bugs early. CD (Continuous Delivery): code is always in a deployable state — new versions can be released at the click of a button. Continuous Deployment: every passing commit is automatically deployed to production. CI/CD reduces risk by deploying small changes frequently rather than large risky releases. Tools: GitHub Actions, GitLab CI, Jenkins, CircleCI, Travis CI.', 1),
('cicd', 'What is a CI/CD pipeline?', 'A pipeline is a series of automated steps triggered by a code event (push, pull request). Typical stages: Trigger (git push) → Install dependencies → Lint and type check → Unit tests → Build (compile, bundle) → Integration tests → Deploy to staging → End-to-end tests → Deploy to production. Each step must pass before the next runs. Failing step sends notification and stops the pipeline. Define pipelines as code in YAML files (.github/workflows/, .gitlab-ci.yml).', 2),
('cicd', 'What is GitHub Actions?', 'GitHub Actions is GitHub''s built-in CI/CD platform. Workflows are defined in .github/workflows/*.yml. Triggered by: push, pull_request, schedule, manual dispatch. Jobs run in parallel by default; use needs: to sequence them. Steps use actions (community marketplace) or shell commands. Secrets stored in repository/organization settings, accessed as ${{ secrets.MY_KEY }}. Runners: GitHub-hosted (Ubuntu, macOS, Windows) or self-hosted. Free tier: 2,000 minutes/month for public repos.', 3),
('cicd', 'What is the difference between blue-green deployment and canary deployment?', 'Blue-Green: run two identical production environments. New version deploys to the inactive one (green). Switch traffic 100% at once via load balancer. Instant rollback by switching back to blue. Requires double the infrastructure. Canary: gradually route a small percentage of traffic (e.g., 5%) to the new version. Monitor for errors/latency. Increase percentage if healthy. Slower rollout but lower risk. Use canary for large user bases where even 5% affected is too many for blue-green.', 4),
('cicd', 'What is Infrastructure as Code (IaC)?', 'IaC manages infrastructure through code files instead of manual GUI/CLI operations. Benefits: version control for infrastructure, reproducible environments, peer review for infrastructure changes, disaster recovery by re-running scripts. Tools: Terraform (cloud-agnostic, declarative HCL), AWS CloudFormation (AWS-native JSON/YAML), Pulumi (use programming languages). Terraform workflow: write .tf files → terraform plan (preview changes) → terraform apply (make changes) → terraform destroy.', 5),
('cicd', 'What is Docker in a CI/CD pipeline?', 'Docker ensures the application builds and runs identically in CI and production. Typical pipeline: Checkout code → docker build -t myapp:$COMMIT_SHA → docker push to registry → SSH to server and docker pull + docker run. Or with Kubernetes: push image → update K8s Deployment image tag → kubectl apply. Benefits: the "works on my machine" problem is eliminated — the CI runner and production run the same Docker image. Always tag images with commit SHA (not just "latest") for traceability.', 6),
('cicd', 'What is a feature flag and how does it relate to CI/CD?', 'Feature flags (feature toggles) allow deploying code to production while controlling whether it''s visible to users. Enables: trunk-based development (merge unfinished features behind a flag), canary releases (enable for 5% of users), A/B testing, instant kill switch for bugs. Decouple deploy from release. Tools: LaunchDarkly, Unleash, Flagsmith, or a simple DB row. Essential for continuous deployment — you can ship code daily even when features aren''t ready for all users.', 7),
('cicd', 'What are environment variables and secrets management in CI/CD?', 'Never hardcode secrets (API keys, passwords, tokens) in code. Inject at runtime via environment variables. In CI/CD: store secrets in the CI provider (GitHub Secrets, GitLab Variables) — they are injected as env vars in the pipeline, never logged. In production: use a secrets manager (AWS Secrets Manager, HashiCorp Vault, Kubernetes Secrets). Rotate secrets regularly. Audit secret access logs. Common mistake: accidentally logging env vars — scrub logs before storing them.', 8);

-- ─── EXTRA BEHAVIORAL QUESTIONS ───────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('behavioral_general', 'Tell me about a time you disagreed with your manager.', 'This tests your ability to push back professionally. Formula: state the context → explain your position with data → describe how you raised it (private 1:1, not in public) → respect the final decision. Key: show you can disagree without being difficult. Example: "My manager wanted to skip code review for a deadline. I raised the risk of bugs in prod, proposed a lightweight async review instead, and we shipped on time without incidents. In hindsight, the manager appreciated the compromise."', 16),
('behavioral_general', 'How do you handle receiving critical feedback?', 'Show you are coachable and don''t get defensive. Formula: I listen fully without interrupting → I thank them for the feedback → I ask clarifying questions if needed → I take action. Example: "My manager told me my code reviews were too slow. I took it seriously, set a 24-hour SLA for myself, and started batching review sessions into my schedule. Six months later, my manager mentioned improvement explicitly in my performance review." Never say "I don''t react well to criticism."', 17),
('behavioral_general', 'Tell me about a time you took initiative without being asked.', 'Shows ownership and proactivity. Look for: noticed a problem no one else was addressing → took ownership → drove it to completion → impacted the team/product positively. Example: "I noticed our test suite ran for 45 minutes, slowing everyone down. Without being assigned, I spent two days parallelizing the tests. It went from 45 to 12 minutes. The team adopted the change and it saved ~30 engineer-hours per month."', 18),
('behavioral_general', 'How do you stay updated with new technologies?', 'Be specific — name actual sources. Good answer: "I read Hacker News and engineering blogs (Stripe, Airbnb, Netflix engineering) weekly. I pick one new technology per quarter to build a small project with. Recently I built a small RAG prototype to understand LLMs practically. I follow key people in my field on Twitter/LinkedIn." Avoid generic: "I read articles." Interviewers want to see genuine curiosity and continuous learning.', 19),
('behavioral_general', 'Tell me about a time you mentored a junior developer.', 'Mentoring questions assess leadership and communication. Show you adapted to their level, gave constructive feedback, and helped them grow — not just that you did the work for them. Example: "I paired with a junior on their first feature. Instead of solving the problem, I asked questions to guide their thinking. When they were stuck on a bug for 2 hours, I had them explain the code out loud — they found the issue themselves. They shipped the feature with minimal changes needed."', 20),
('behavioral_general', 'Describe your approach to learning a new codebase quickly.', 'Shows methodology. Good answer: (1) Run the app locally and understand what it does end-to-end. (2) Read the README, architecture docs, and onboarding guide. (3) Find the entry points (main function, routing files, event handlers). (4) Trace a key user journey through the code. (5) Make a small, safe change and see the effect. (6) Talk to teammates — 10 minutes with a human beats 2 hours reading code. (7) Write down your understanding as you go.', 21),
('behavioral_general', 'How do you handle ambiguity or unclear requirements?', 'Strong engineers clarify before building. Show: identify what you don''t know → ask the right people → document assumptions → verify your understanding. Example: "Our PM gave us a vague requirement: ''improve the onboarding experience.'' I ran a 30-minute meeting with PM, designer, and a CS rep to define specific success metrics (activation rate, time-to-first-value). We agreed on 3 concrete changes. This saved us from building something unmeasurable." Never say "I just start coding."', 22),
('behavioral_general', 'Tell me about your biggest professional accomplishment.', 'This is your highlight reel moment. Prepare a story you are genuinely proud of. Use STAR: Situation (context), Task (your responsibility), Action (specific steps you took), Result (quantified impact). Pick something technical if interviewing for engineering, people-impact if interviewing for a leadership role. Be specific with numbers: "reduced load time by 60%", "increased signups by 22%", "saved $40k/year in infrastructure costs". Avoid vague: "delivered the project on time."', 23),
('behavioral_general', 'How do you prioritize when you have too much work?', 'Shows maturity and judgment. Formula: clarify deadlines and impact → communicate proactively → do the most important thing first. Example: "When I have competing high-priority items, I bring them to my manager with a proposed ranking and the tradeoffs of each order. I prefer to surface the conflict early rather than silently deprioritize something important. I use a simple framework: urgent + important first, delegate urgent + less important, schedule important + not urgent."', 24),
('behavioral_general', 'Describe a time you had to work with a difficult colleague.', 'Do NOT say you have never had a difficult colleague — that is not credible. Formula: describe the friction factually (no drama) → explain the impact on work → describe how YOU adapted → positive outcome. Avoid blaming. Example: "A colleague and I had different coding styles and it slowed code reviews. I initiated a team session where we agreed on standards and added a linter to enforce them automatically. It removed the subjective friction from reviews entirely."', 25);

-- ─── EXTRA JAVASCRIPT QUESTIONS ───────────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('javascript', 'What is a WeakMap and WeakSet?', 'WeakMap: a Map whose keys must be objects, and keys are held weakly — if the key object has no other references, it can be garbage collected (along with its WeakMap entry). WeakSet: similar — a set of weakly-held objects. Neither is iterable (no forEach, no size). Use case: storing metadata about DOM nodes or objects without preventing their GC. Example: WeakMap<Element, {clicks: number}> tracks data per element; when the element is removed from the DOM, the entry is automatically cleaned up.', 13),
('javascript', 'What is the difference between a shallow copy and deep copy?', 'Shallow copy: copies the top-level properties. Nested objects are still shared references. Methods: Object.assign({}, obj), spread ({...obj}), Array.from(arr), slice(). Deep copy: recursively copies all nested objects — no shared references. Methods: structuredClone(obj) (built-in, modern), JSON.parse(JSON.stringify(obj)) (fails for functions, undefined, Dates, circular refs). Libraries: lodash.cloneDeep. Use shallow copy for simple flat objects, deep copy when mutating nested objects independently.', 14),
('javascript', 'What are generators in JavaScript?', 'Generators are functions that can pause and resume, yielding values on demand. function* gen() { yield 1; yield 2; yield 3; }. Calling gen() returns an iterator. Each next() call resumes until the next yield. Use for: lazy evaluation of infinite sequences, async flow control (basis of early async/await implementations), custom iterables. Infinite sequence example: function* integers() { let n=0; while(true) yield n++; }. Generators are the mechanism behind for...of iteration on custom objects.', 15),
('javascript', 'What is a Symbol in JavaScript?', 'Symbol is a primitive type that creates a unique identifier — every Symbol() call returns a distinct value even with the same description. Symbol.for("key") creates a global shared symbol. Use as object keys to avoid name collisions in libraries: const LOG_LEVEL = Symbol("logLevel"). Well-known symbols: Symbol.iterator (make an object iterable), Symbol.toPrimitive (custom type coercion), Symbol.hasInstance (instanceof behavior). Symbols are not enumerable in for...in or Object.keys().', 16),
('javascript', 'What is the Proxy object in JavaScript?', 'Proxy wraps an object and intercepts fundamental operations (get, set, has, deleteProperty, apply). new Proxy(target, handler) where handler defines traps. Example: validation proxy: const p = new Proxy({}, { set(obj, prop, val) { if (typeof val !== "number") throw TypeError; obj[prop] = val; return true; } }). Used in Vue 3 reactivity system (replaced Object.defineProperty), ORM query builders, access logging, and read-only views of objects. Reflect.set/get provides default behavior in traps.', 17),
('javascript', 'What are tagged template literals?', 'Tagged templates allow processing template literals with a function. tag`Hello ${name}` calls tag(strings, ...values) where strings is an array of static string parts. Use cases: styled-components (CSS-in-JS: css`color: ${primary}`), SQL query builders (sanitize interpolated values to prevent injection: sql`SELECT * FROM users WHERE id=${id}`), i18n libraries. More powerful than regular template literals because you control how the parts are assembled.', 18),
('javascript', 'What is the difference between microtasks and macrotasks?', 'Microtasks (Promise callbacks, queueMicrotask, MutationObserver) run after the current task completes, before the event loop picks the next macrotask. Macrotasks (setTimeout, setInterval, setImmediate, I/O callbacks) are scheduled for future event loop iterations. After each macrotask, ALL pending microtasks run. Implication: Promise.resolve().then(() => console.log(1)); setTimeout(() => console.log(2)) — logs 1 then 2, even though setTimeout has 0ms delay.', 19),
('javascript', 'What are common JavaScript design patterns?', 'Module: encapsulate private state (IIFE, or ES modules). Observer/Pub-Sub: subscribe to events (EventEmitter, custom implementations). Factory: create objects without new (createUser() instead of new User()). Singleton: one instance per app (modules are singletons by default in ES). Decorator: wrap functions/classes to add behavior (same idea as Python decorators, now a JS proposal). Strategy: swap algorithms at runtime (pass function as argument). Proxy: intercept operations (covered separately). Patterns solve recurring problems — name-drop them in architecture discussions.', 20);

-- ─── EXTRA SYSTEM DESIGN QUESTIONS ───────────────────────────────────────────
INSERT INTO study_questions (topic_id, question, answer, sort_order) VALUES
('system_design_general', 'How would you design a real-time chat system?', 'Components: WebSocket server (long-lived connection per user), message storage (DynamoDB or Cassandra — append-heavy), user presence service (Redis HSET per user with TTL), notification service (push if offline). Flow: User A sends message → server stores in DB → publishes to pub/sub channel → all connected clients in the conversation receive it via WebSocket. For scale: partition WebSocket servers by user ID hash, use Redis pub/sub or Kafka for fan-out across servers. One-on-one: simpler. Group chats with 100k members: fan-out on write is too expensive, use fan-out on read.', 13),
('system_design_general', 'What is the circuit breaker pattern?', 'Circuit breaker prevents cascading failures when a downstream service is unhealthy. States: Closed (normal — requests flow through), Open (downstream is failing — requests fail fast without calling it), Half-Open (probe: allow a few requests to test recovery, switch to Closed if successful). Configure: trip after N failures in M seconds, wait T seconds before probing. Implemented in: Netflix Hystrix (deprecated), Resilience4j, Envoy sidecar. Without circuit breakers, a slow database can bring down your entire API.', 14),
('system_design_general', 'What is database connection pooling?', 'Opening a database connection is expensive (TCP handshake, auth, SSL). Connection pooling maintains a cache of open connections reused across requests. Pool size = number of concurrent DB connections maintained. Too small → requests queue waiting for a connection. Too large → DB is overwhelmed. Rule of thumb: 10-20 connections per application server for PostgreSQL. Libraries: HikariCP (Java), pg-pool (Node.js), SQLAlchemy (Python). In Kubernetes: use PgBouncer as a connection pooler to handle thousands of app pods connecting to one PostgreSQL.', 15),
('system_design_general', 'What is the difference between stateful and stateless services?', 'Stateless service: each request is independent — no memory of previous requests. Server can be replaced or scaled horizontally without impact. Session data stored externally (Redis, DB, JWT in the request). Stateful service: maintains state across requests (game session, WebSocket connection, long-running transaction). Harder to scale horizontally — client must reconnect to the same server (sticky sessions) or state must be shared. Design principle: make services stateless wherever possible. Push state to databases/caches.', 16),
('system_design_general', 'How do you design for high availability (HA)?', 'HA means the system is available even when components fail. Key principles: eliminate single points of failure (everything has at least 2 instances), use health checks and automatic failover (load balancer removes unhealthy instances), design for graceful degradation (serve cached/stale data if DB is slow), multi-availability zone deployment, database replication (read replicas + automatic failover), CDN for static assets. Measure: availability = uptime / (uptime + downtime). 99.9% = 8.7h downtime/year, 99.99% = 52 min/year.', 17),
('system_design_general', 'How would you design an authentication system?', 'Options: Session-based (server stores session in Redis, sends cookie — stateful) vs JWT-based (server sends signed token, client sends it on each request — stateless). JWT: no DB lookup per request, but harder to revoke (short expiry + refresh tokens). OAuth2: delegate auth to Google/GitHub/etc. Store passwords with bcrypt (cost factor 10-12) or Argon2 — never MD5/SHA1. Rate-limit login attempts. Implement refresh tokens in an HttpOnly cookie (prevents XSS). Use HTTPS everywhere. Consider: magic links, passkeys (WebAuthn) for passwordless.', 18),
('system_design_general', 'What is consistent hashing?', 'Consistent hashing minimizes key redistribution when nodes are added/removed from a distributed system (cache servers, shards). Keys and nodes are mapped to a ring (0–2^32). A key belongs to the first node clockwise from its position. Add a node: only keys between it and its predecessor move. Remove a node: only its keys move to the next node. Without consistent hashing (modulo hashing), adding/removing a node remaps most keys — catastrophic for a cache. Used in: DynamoDB, Cassandra, Memcached, Redis Cluster.', 19),
('system_design_general', 'What is idempotency and why does it matter in APIs?', 'An idempotent operation produces the same result regardless of how many times it is called. GET, PUT, DELETE are idempotent. POST is not idempotent by default. Why it matters: networks are unreliable — clients retry requests on timeout. If POST /charge is not idempotent, a retry causes a double charge. Solution: client sends a unique idempotency key (UUID) in the request header. Server checks if it has seen this key — if yes, returns the cached response without re-processing. Stripe, PayPal, and all major payment APIs implement idempotency keys.', 20);
